// This file is part of SNMP#NET8.
// 
// SNMP#NET8 is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// SNMP#NET8 is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with SNMP#NET8.  If not, see <http://www.gnu.org/licenses/>.
// 
using SnmpSharpNet8.Exceptions;
using SnmpSharpNet8.Types;
using System.Security.Cryptography;

namespace SnmpSharpNet8.Security;
/// <summary>
/// Authentication digest interface. Interface defines authentication methods
/// for incoming and outgoing requests.
/// </summary>
public class Authentication {
    private readonly int authenticationLength;

    private readonly Dictionary<AuthenticationDigest, (HashAlgorithm, HMAC, int)> algos = new(){
        { AuthenticationDigest.MD5,    (MD5.Create(),    new HMACMD5(),    12) },
        { AuthenticationDigest.SHA1,   (SHA1.Create(),   new HMACSHA1(),   12) },
        { AuthenticationDigest.SHA256, (SHA256.Create(), new HMACSHA256(), 24) },
        { AuthenticationDigest.SHA384, (SHA384.Create(), new HMACSHA384(), 32) },
        { AuthenticationDigest.SHA512, (SHA512.Create(), new HMACSHA512(), 48) }
    };
    /// <summary>
    /// Returns the size of the authentification header length. This value represent the size of the digest
    /// that is stored inside the USM authentication parameters header.
    /// </summary>
    public virtual int AuthentificationHeaderLength => authenticationLength;
    /// <summary>
    /// Returns the size of the native algorithm. This value does not represent the size of the digest
    /// that is stored inside the USM authentication parameters header but real length generated by it.
    /// </summary>
    public virtual int DigestLength => HashAlgo.HashSize / 8;
    public virtual HashAlgorithm HashAlgo { get; }
    public virtual HMAC HmacProvider { get; }
    /// <summary>
    /// Return authentication protocol name.
    /// </summary>
    public virtual string Name { get; }
    public Authentication(AuthenticationDigest algo) {
        (HashAlgorithm hashAlgo, HMAC hmac, int length) = algos[algo];
        HashAlgo = hashAlgo;
        HmacProvider = hmac;
        authenticationLength = length;
        Name = $"HMAC-{HashAlgo.GetType().Name}";
    }
    public Authentication(HashAlgorithm hashAlgo, HMAC hmacProvider, int headerLength) {
        HashAlgo = hashAlgo;
        HmacProvider = hmacProvider;
        authenticationLength = headerLength;
        Name = $"HMAC-{HashAlgo.GetType().Name}";
    }
    /// <summary>
    /// Authentication outgoing message
    /// </summary>
    /// <param name="userPassword">Authentication secret</param>
    /// <param name="engineId">SNMP version 3 agent engine id</param>
    /// <param name="wholeMessage">Message to authenticate</param>
    /// <returns>Authentication parameters</returns>
    public byte[] Authenticate(byte[] userPassword, byte[] engineId, byte[] wholeMessage) {
        byte[] result = new byte[AuthentificationHeaderLength];
        byte[] authKey = PasswordToKey(userPassword, engineId);
        HmacProvider.Key = authKey;
        byte[] hash = HmacProvider.ComputeHash(wholeMessage);
        Buffer.BlockCopy(hash, 0, result, 0, AuthentificationHeaderLength);
        return result;
    }
    /// <summary>
    /// Authentication outgoing message
    /// </summary>
    /// <param name="authKey">Authentication key</param>
    /// <param name="wholeMessage">Message to authenticate</param>
    /// <returns>Authentication parameters</returns>
    public byte[] Authenticate(byte[] authKey, byte[] wholeMessage) {
        byte[] result = new byte[AuthentificationHeaderLength];
        HmacProvider.Key = authKey;
        byte[] hash = HmacProvider.ComputeHash(wholeMessage);
        Buffer.BlockCopy(hash, 0, result, 0, AuthentificationHeaderLength);
        return result;
    }
    /// <summary>
    /// Authenticate incoming messages
    /// </summary>
    /// <param name="authentiationSecret">Authentication user secret (password)</param>
    /// <param name="engineId">SNMP agent authoritative engine id</param>
    /// <param name="authenticationParameters">Authentication parameters from the incoming packet</param>
    /// <param name="wholeMessage">Entire message with authentication parameters field zeroed out</param>
    /// <returns>True if packet is authenticated, otherwise false.</returns>
    public bool AuthenticateIncomingMsg(byte[] authentiationSecret, byte[] engineId, byte[] authenticationParameters, MutableByte wholeMessage) {
        byte[] authKey = PasswordToKey(authentiationSecret, engineId);
        HmacProvider.Key = authKey;
        byte[] hash = HmacProvider.ComputeHash(wholeMessage, 0, wholeMessage.Length);
        MutableByte myhash = new(hash, AuthentificationHeaderLength);
        if (myhash.Equals(authenticationParameters)) {
            return true;
        }
        return false;
    }
    /// <summary>
    /// Authenticate incoming messages
    /// </summary>
    /// <param name="authKey">Authentication key</param>
    /// <param name="authenticationParameters">Authentication parameters from the incoming packet</param>
    /// <param name="wholeMessage">Entire message with authentication parameters field zeroed out</param>
    /// <returns>True if packet is authenticated, otherwise false.</returns>
    public bool AuthenticateIncomingMsg(byte[] authKey, byte[] authenticationParameters, MutableByte wholeMessage) {
        HmacProvider.Key = authKey;
        byte[] hash = HmacProvider.ComputeHash(wholeMessage, 0, wholeMessage.Length);
        MutableByte myhash = new(hash, AuthentificationHeaderLength);
        if (myhash.Equals(authenticationParameters)) {
            return true;
        }
        return false;
    }
    /// <summary>
    /// Compute hash using authentication protocol.
    /// </summary>
    /// <param name="data">Data to hash</param>
    /// <param name="offset">Compute hash from the source buffer offset</param>
    /// <param name="count">Compute hash for source data length</param>
    /// <returns>Hash value</returns>
    public byte[] ComputeHash(byte[] data, int offset, int count) {
        byte[] res = HashAlgo.ComputeHash(data, offset, count);
        HashAlgo.Clear();
        return res;
    }
    public static Authentication? GetInstance(AuthenticationDigest authProtocol) {
        if (authProtocol == AuthenticationDigest.None) {
            return null;
        }
        return new(authProtocol);
    }
    /// <summary>
    /// Convert password to a key
    /// </summary>
    /// <param name="passwordString">Authentication key</param>
    /// <param name="engineID">Authoritative engine id</param>
    /// <returns>Key value</returns>
    public byte[] PasswordToKey(byte[] passwordString, byte[] engineID) {
        // key length has to be at least 8 bytes long (RFC3414)
        if (passwordString == null || passwordString.Length < 8)
            throw new SnmpAuthenticationException("Secret key is too short.");

        int password_index = 0;
        int count = 0;

        byte[] sourceBuffer = new byte[1048576];
        byte[] buf = new byte[64];
        while (count < 1048576) {
            for (int i = 0; i < 64; ++i) {
                buf[i] = passwordString[password_index++ % passwordString.Length];
            }
            Buffer.BlockCopy(buf, 0, sourceBuffer, count, buf.Length);
            count += 64;
        }

        byte[] digest = HashAlgo.ComputeHash(sourceBuffer);

        MutableByte tmpbuf = new();
        tmpbuf.Append(digest);
        tmpbuf.Append(engineID);
        tmpbuf.Append(digest);
        byte[] key = HashAlgo.ComputeHash(tmpbuf);

        return key;
    }
}
