// This file is part of SNMP#NET8.
// 
// SNMP#NET8 is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// SNMP#NET8 is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with SNMP#NET8.  If not, see <http://www.gnu.org/licenses/>.
// 
using SnmpSharpNet8.Exceptions;
using System.Buffers.Binary;
using System.Security.Cryptography;

namespace SnmpSharpNet8.Security;
/// <summary>AES privacy protocol implementation class.</summary>
public class PrivacyAES : IPrivacyProtocol {
    /// <summary>
    /// Salt value
    /// </summary>
    protected long _salt = Random.Shared.NextInt64();
    /// <summary>
    /// AES protocol key bytes. Valid values are 16 (for AES128), 24 (AES192) or 32 (AES256).
    /// </summary>
    protected int _keyBytes = 16; // Default is 128bit AES protocol

    /// <summary>
    /// AES implementation supports extending of a short encryption key. Always returns true.
    /// </summary>
    public bool CanExtendShortKey => true;
    /// <summary>
    /// Privacy protocol name. Returns string "AES"
    /// </summary>
    public virtual string Name => "AES";
    /// <summary>
    /// Get maximum encryption/decryption key length required by the protocol.
    /// </summary>
    public int MaximumKeyLength => _keyBytes;
    /// <summary>
    /// Get minimum encryption/decryption key length required by the protocol.
    /// </summary>
    public int MinimumKeyLength => _keyBytes;
    /// <summary>
    /// Get length of the privacy parameters byte array that is generated by the encryption method and used by the
    /// decryption method.
    /// </summary>
    public int PrivacyParametersLength => 8;

    /// <summary>
    /// Standard constructor.
    /// </summary>
    /// <param name="keyBytes">Key size in bytes. Acceptable values are
    /// 16 = 128-bit key size, 24 = 192-bit key size, or 32 = 256-bit key size.</param>
    public PrivacyAES(int keyBytes) {
		if (keyBytes != 16 && keyBytes != 24 && keyBytes != 32)
			throw new ArgumentOutOfRangeException(nameof(keyBytes), "Valid key sizes are 16, 24 and 32 bytes.");
		_keyBytes = keyBytes;
		Random rand = new();
		_salt = Convert.ToInt64(rand.Next(1, int.MaxValue));
	}
    /// <summary>
    /// Decrypt <see cref="ScopedPdu"/> BER encoded byte array.
    /// </summary>
    /// <param name="cryptedData">Encrypted data byte array</param>
    /// <param name="offset">Offset within the buffer to start decryption process from</param>
    /// <param name="length">Length of data to decrypt</param>
    /// <param name="key">Decryption key</param>
    /// <param name="engineBoots">Authoritative engine boots value. Retrieved as part of SNMP v3 discovery procedure</param>
    /// <param name="engineTime">Authoritative engine time value. Retrieved as part of SNMP v3 discovery procedure</param>
    /// <param name="privacyParameters">Privacy parameters parsed from the incoming packet.</param>
    /// <returns>Byte array containing decrypted <see cref="ScopedPdu"/> in BER encoded format.</returns>
    public byte[] Decrypt(
            byte[] encryptedData,
            byte[] key,
            int engineBoots,
            int engineTime,
            byte[] privacyParameters
        ) {
        if (key == null || key.Length < MinimumKeyLength)
            throw new ArgumentOutOfRangeException(nameof(key), "Invalid key length");

        byte[] iv = new byte[16];
        int len = Math.Min(key.Length, MaximumKeyLength);
        try {
            BinaryPrimitives.WriteInt32BigEndian(iv.AsSpan(0, 4), engineBoots);
            BinaryPrimitives.WriteInt32BigEndian(iv.AsSpan(4, 4), engineTime);

            privacyParameters.AsSpan().CopyTo(iv.AsSpan(8));

            using Aes rm = Aes.Create();
            rm.KeySize = _keyBytes * 8;
            rm.FeedbackSize = 128;
            rm.BlockSize = 128;
            rm.Padding = PaddingMode.Zeros;
            rm.Mode = CipherMode.CFB;
            rm.Key = key[..len];
            rm.IV = iv;
            using ICryptoTransform cryptor = rm.CreateDecryptor();

            if ((encryptedData.Length % _keyBytes) != 0) {
                int paddedLength = (encryptedData.Length + 15) / 16 * 16;
                byte[] decryptBuffer = new byte[paddedLength];
                encryptedData.AsSpan(0, encryptedData.Length).CopyTo(decryptBuffer);
                return cryptor.TransformFinalBlock(decryptBuffer, 0, paddedLength)[..encryptedData.Length];
            }
            return cryptor.TransformFinalBlock(encryptedData, 0, encryptedData.Length);
        } catch (Exception ex) {
            throw new SnmpPrivacyException("Exception was thrown while AES privacy protocol was decrypting data.", ex);
        } finally {
            CryptographicOperations.ZeroMemory(iv);
        }
    }
    /// <summary>
    /// Encrypt <see cref="ScopedPdu"/> data BER encoded in a byte array.
    /// </summary>
    /// <param name="unencryptedData">BER encoded <see cref="ScopedPdu"/> byte array that needs to be encrypted</param>
    /// <param name="offset">Offset within the BER encoded byte array to start encryption operation from.</param>
    /// <param name="length">Length of data to encrypt</param>
    /// <param name="key">Encryption key</param>
    /// <param name="engineBoots">Authoritative engine boots value. Retrieved as part of SNMP v3 discovery process.</param>
    /// <param name="engineTime">Authoritative engine time value. Retrieved as part of SNMP v3 discovery process.</param>
    /// <param name="privacyParameters">Byte array that will receive privacy parameters information that is the result of the
    /// encryption procedure.</param>
    /// <param name="authDigest">Authentication digest reference. Not used by AES protocol and can be null</param>
    /// <returns>Byte array containing encrypted <see cref="ScopedPdu"/> BER encoded data</returns>
    public byte[] Encrypt(
            byte[] unencryptedData,
            byte[] key,
            int engineBoots,
            int engineTime,
            out byte[] privacyParameters,
            Authentication? _ = null
        ) {
        if (key == null || key.Length < _keyBytes)
            throw new ArgumentOutOfRangeException(nameof(key), "Invalid key length");

        byte[] iv = new byte[16];
        byte[] pkey = new byte[MinimumKeyLength];
        long salt = NextSalt();
        BinaryPrimitives.WriteInt32BigEndian(iv.AsSpan(0, 4), engineBoots);
        BinaryPrimitives.WriteInt32BigEndian(iv.AsSpan(4, 4), engineTime);
        privacyParameters = BitConverter.GetBytes(salt);
        Array.Reverse(privacyParameters);
        privacyParameters.AsSpan().CopyTo(iv.AsSpan(8));
        try {
            using Aes rm = Aes.Create();
            rm.KeySize = _keyBytes * 8;
            rm.FeedbackSize = 128;
            rm.BlockSize = 128;
            rm.Padding = PaddingMode.Zeros;
            rm.Mode = CipherMode.CFB;
            key.CopyTo(pkey, 0);
            rm.Key = pkey;
            rm.IV = iv;
            return rm
                .CreateEncryptor()
                .TransformFinalBlock(unencryptedData, 0, unencryptedData.Length)[..unencryptedData.Length];
        } catch (Exception ex) {
            throw new SnmpPrivacyException("Exception was thrown while AES privacy protocol was encrypting data.", ex);
        } finally {
            CryptographicOperations.ZeroMemory(iv);
            CryptographicOperations.ZeroMemory(pkey);
        }
    }
    /// <summary>
    /// Some protocols support a method to extend the encryption or decryption key when supplied key
    /// is too short.
    /// </summary>
    /// <param name="shortKey">Key that needs to be extended</param>
    /// <param name="password">Privacy password as configured on the SNMP agent.</param>
    /// <param name="engineID">Authoritative engine id. Value is retrieved as part of SNMP v3 discovery procedure</param>
    /// <param name="authProtocol">Authentication protocol class instance cast as <see cref="IAuthenticationDigest"/></param>
    /// <returns>Extended key value</returns>
    public byte[]? ExtendShortKey(byte[] shortKey, byte[] password, byte[] engineID, Authentication authProtocol) {
        byte[] extKey = new byte[MinimumKeyLength];
        byte[] lastKeyBuf = new byte[shortKey.Length];
        Array.Copy(shortKey, lastKeyBuf, shortKey.Length);
        int keyLen = shortKey.Length > MinimumKeyLength ? MinimumKeyLength : shortKey.Length;
        Array.Copy(shortKey, extKey, keyLen);
        while (keyLen < MinimumKeyLength) {
            byte[] tmpBuf = authProtocol.PasswordToKey(lastKeyBuf, engineID);
            if (tmpBuf == null) {
                return null;
            }
            if (tmpBuf.Length <= (MinimumKeyLength - keyLen)) {
                Array.Copy(tmpBuf, 0, extKey, keyLen, tmpBuf.Length);
                keyLen += tmpBuf.Length;
            } else {
                Array.Copy(tmpBuf, 0, extKey, keyLen, MinimumKeyLength - keyLen);
                keyLen += (MinimumKeyLength - keyLen);
            }
            lastKeyBuf = new byte[tmpBuf.Length];
            Array.Copy(tmpBuf, lastKeyBuf, tmpBuf.Length);
        }
        return extKey;
    }
    /// <summary>
    /// Calculates and returns length of the buffer that is the result of the encryption method.
    /// </summary>
    /// <param name="scopedPduLength">Length of the buffer that is needs to be encrypted.</param>
    /// <returns>Length of the encrypted byte array after the call to Encrypt method.</returns>
    public int GetEncryptedLength(int scopedPduLength) => scopedPduLength;
    /// <summary>
    /// Get next salt Int64 value. Used internally to encrypt data.
    /// </summary>
    /// <returns>Random Int64 value</returns>
    protected long NextSalt() {
        long next = Interlocked.Increment(ref _salt);
        return next;
    }
	/// <summary>
	/// Convert privacy password into encryption key using packet authentication hash.
	/// </summary>
	/// <param name="secret">Privacy user secret</param>
	/// <param name="engineId">Authoritative engine id of the snmp agent</param>
	/// <param name="authProtocol">Authentication protocol</param>
	/// <returns>Encryption key</returns>
	/// <exception cref="SnmpPrivacyException">Thrown when key size is shorter then MinimumKeyLength</exception>
	public byte[]? PasswordToKey(byte[] secret, byte[] engineId, Authentication authProtocol) {
		if (secret == null || secret.Length < 8)
			throw new SnmpPrivacyException("Invalid privacy secret length.");
		byte[] key = authProtocol.PasswordToKey(secret, engineId);
        return key.Length < MinimumKeyLength ?
			ExtendShortKey(key, secret, engineId, authProtocol) :
		    key;
	}
}
